on: issue_comment

jobs:
  check-pr-requirements:
    if: github.event.issue.pull_request && github.event.label.name != 'skip changelog' 
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Retrieve output if changelog entry exists
        run: echo "${{ github.event }}" 
      - name: Check if changelog entry exists
        uses: ./ #uses action in root repository
        id: check-changelog
        with:
          pr-body: ${{ github.event.issue.body }}
      - name: Retrieve output if changelog entry exists
        run: echo "${{ steps.check-changelog.outputs.approved-changelog-entry}}"