on:
  pull_request:
    types: [opened, reopened, edited, labeled]

jobs:
  check-pr-requirements:
    if: ${{ !contains(github.event.labels.*.name, 'skip changelog') }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_EVENT: ${{ github.event.labels }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Retrieve output if changelog entry exists
        run: echo "$GITHUB_EVENT" 
      - name: Check if changelog entry exists
        uses: ./ #uses action in root repository
        id: check-changelog
        with:
          pr-body: ${{ github.event.body }}
      - name: Retrieve output if changelog entry exists
        run: echo "$GITHUB_EVENT"